### ISSUE TITLE
Fix: Improve Username Visibility in Light Mode for Enhanced Readability

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#102]
Description: In light mode, the username's text visibility is poor due to insufficient contrast with the background. This issue involves adjusting the color of the username text or modifying the background to enhance readability and ensure optimal user experience in both light and dark modes. The fix should include testing across different screen resolutions and devices to maintain consistent visual clarity.

**Comment by Jash2606** [comment]
Hey @Gyanthakur ,I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by Vishrut99** [comment]
Hey @Gyanthakur i can fix this issue can you please assign me ?

**Comment by Gyanthakur** [comment]
> Hey @Gyanthakur ,I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

assigned to @Jash2606

**Comment by Gyanthakur** [comment]
> Hey @Gyanthakur i can fix this issue can you please assign me ?

you should create new issue

**Comment by Jash2606** [comment]
Hey @Gyanthakur, could you suggest a background color? Were you thinking of something like the same gradient as the footer, or did you have a different shade in mind?
