### ISSUE TITLE
Border is missing

### ISSUE THREAD

**Issue by chaanakyaaM** [Gyanthakur/Dev_Profiles#112]
![image](https://github.com/user-attachments/assets/44bfd9a2-cfce-463f-b0cb-e9a0f75c7026)
![image](https://github.com/user-attachments/assets/7d374fca-d9f7-4864-8ce0-b294696666e0)

There are few profiles where the border is not visible as you an see it in the images, i would like to fix it.

@Gyanthakur 
Could you kindly assign this to me under Hacktoberfest, I would send the PR as soon as possible.

**Comment by ADeshmukh80** [comment]
please assign this task to me
