### ISSUE TITLE
Add The Hover Effect in the footer

### ISSUE THREAD

**Issue by SaumyaSubham** [Gyanthakur/Dev_Profiles#122]
Hello @Gyanthakur 

I want to add the hover effect in the footer so that the users can easily navigate to the menu options i.e., Home, About, Project Section, Contact
Kindly assign me this issue under Hacktoberfest 2024

![Screenshot 2024-10-02 191801](https://github.com/user-attachments/assets/fa772d3b-9f98-46df-948c-5866693cab8c)

**Comment by souvikpramanikgit** [comment]
I want to work on this issue

**Comment by k562** [comment]
Hey @Gyanthakur ,Can i work on this issue ?
