### ISSUE TITLE
Adding CopyRight Page 

### ISSUE THREAD

**Issue by SwarSpark** [Gyanthakur/Dev_Profiles#123]
I want to work on this issue, can you assign me this issue

Linking The Copyright page in footer.
I kindly request to be assigned this issue.

Thank you!

Hactoberfest !!!

**Comment by souvikpramanikgit** [comment]
I want to work in this issue.

**Comment by Gyanthakur** [comment]
> I want to work in this issue.

Yes this issue assigned to you make the changes accordingly.

**Comment by Gyanthakur** [comment]
> I want to work in this issue.
