### ISSUE TITLE
Add link to the website in the website name

### ISSUE THREAD

**Issue by justin212407** [Gyanthakur/Dev_Profiles#187]
Description

The header where the website's name is displayed does not have a link that redirects to the same website.

Expected Behavior

it should redirect to the same website.

Screenshots:

![Screenshot 2024-10-07 181355](https://github.com/user-attachments/assets/6c1b758f-3a44-4587-b02e-3072616767ed)

How to Reproduce

It is visible every time you click on the website header.

I would like to be assigned to this issue under hacktoberfest and would like to work on it.

**Comment by NAMAN-Github01** [comment]
Please assign

**Comment by AnirudhSinghRajora** [comment]
Please accept my PR

**Comment by Gyanthakur** [comment]
#189
