### ISSUE TITLE
Change UI

### ISSUE THREAD

**Issue by chaanakyaaM** [Gyanthakur/Dev_Profiles#236]
## 📝 Description
I would like to change the design of the home page,projects page,about section.

### 📷 Screenshot or Visual Reference (optional)
Like this:
![image](https://github.com/user-attachments/assets/30f8196b-5954-49e7-a4c6-1e849c62eb9b)

**Comment by Snehalgupta-07** [comment]
hi!  i can do this task can u pls assign it to me :)
