### ISSUE TITLE
DOC: Update Contributing.md 

### ISSUE THREAD

**Issue by Dishaaa-T** [Gyanthakur/Dev_Profiles#254]
## 📝 Description
Add clear instruction with git command snippets on how to fork repo, how to create branch, how to add and commit your changes

### 📷 Screenshot or Visual Reference (optional)

![image](https://github.com/user-attachments/assets/3494e472-9a34-43e6-bcc9-320abab5855d)

## 💡 Enhancement / Feature Request (if applicable)
This will help beginners and first time contributors to make their first PRs

**Comment by Gyanthakur** [comment]
ok @Dishaaa-T push the changes
