### ISSUE TITLE
Updating the old logo of twitter to X in footer section

### ISSUE THREAD

**Issue by ratna-jaiswal** [Gyanthakur/Dev_Profiles#255]
I wanted to Update the old twitter logo which is "X" on the profile page and the older one "bird" on the other pages like about, projects and contact pages

here attaching the screen shots of all the pages footer section

![Screenshot (1255)](https://github.com/user-attachments/assets/e8e3c5a0-b9b3-44bb-a039-5f9c1e6cd14d)
![Screenshot (1254)](https://github.com/user-attachments/assets/6d6d6878-bc60-4cda-b31c-60c176cafb1c)
![Screenshot (1253)](https://github.com/user-attachments/assets/a22087ee-64b1-4ec9-b908-1de6a30e8f82)
![Screenshot (1252)](https://github.com/user-attachments/assets/8cabc099-2828-4bca-9a26-a49386723df6)

**Comment by ratna-jaiswal** [comment]
@Gyanthakur pls assign this issue to me

**Comment by Gyanthakur** [comment]
> @Gyanthakur pls assign this issue to me

Okey @ratna-jaiswal push the changes

**Comment by Gyanthakur** [comment]
#265 Completed
