### ISSUE TITLE
Want to Enchance  Navabar  buttons 

### ISSUE THREAD

**Issue by Kavita1928** [Gyanthakur/Dev_Profiles#267]
will modify it to match with website 
![Screenshot 2024-10-13 122814](https://github.com/user-attachments/assets/3a3d32f7-6de3-49f3-a5fc-446614bb7fdd)
## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Step 1
  2. Step 2
  3. Step 3
- **Expected behavior:** What should happen?
- **Actual behavior:** What happened instead?
- **Environment (if applicable):**
  - Browser/OS: 
  - Device:

**Comment by Gyanthakur** [comment]
@Kavita1928 Check the #252 issue and work on it.
