### ISSUE TITLE
Cards Not Updating on Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by Abhik004** [Gyanthakur/Dev_Profiles#296]
## 📝 Description
When toggling between dark and light modes, only the background color of the page changes, but the card components retain their color, which causes visual inconsistencies. The card backgrounds and text colors should also switch between dark and light modes.

### 📷 Screenshot or Visual Reference (optional)

![Screenshot 2024-10-16 105047](https://github.com/user-attachments/assets/b77f337c-b6f6-4d94-8f2c-29fce1a5c3ef)
![Screenshot 2024-10-16 105034](https://github.com/user-attachments/assets/66287afa-4566-4367-91c8-bde45aa615f8)

## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
1.Load the page in light mode.
2.Toggle to dark mode.
3.Observe that the page background changes, but the card colors do not update accordingly.
- **Expected behavior:** The background and text color of the cards should also toggle to match the selected theme (dark/light).
- **Actual behavior:** The card components remain unchanged when toggling themes, causing them to stand out against the rest of the UI.

## 🌐 Additional Context
This issue impacts overall UI consistency and user experience, particularly when switching to dark mode. Proper theme handling across all components is essential for accessibility and design uniformity.

**Comment by Abhik004** [comment]
Kindly assign me this issue @Gyanthakur

**Comment by Gyanthakur** [comment]
push the changes.

**Comment by Gyanthakur** [comment]
@Abhik004 what's your update?

**Comment by Sushil010** [comment]
@Gyanthakur I saw the issue was open and previous contributor was not responding so i have made changes and opened a PR. Will be glad to hear any changes if still required
