### ISSUE TITLE
enhancing the ui for contact-us page for better user interaction and engagement

### ISSUE THREAD

**Issue by dhruv-4444** [Gyanthakur/Dev_Profiles#297]
hey @Gyanthakur i will able to help you enhancing the ui for contact us page for better user engagement and will also make that responsive so that user can access it from any device.
assign me this task, with hacktoberfest labels.
Thanks in Advance

**Comment by rohitja26** [comment]
hey @Gyanthakur  I can help you to make the contact us page look good and also align with your overall ui as I can see the colors and font styling is not same as the overall UI part I can help you to resolve that things.

![Screenshot 2024-10-16 170741](https://github.com/user-attachments/assets/ceeed97b-173f-4670-b6f5-d8c739e268cc)


you can also see that the contact us banner is bigger as compare to other bars i.e. Go to profile section etc.  also the color of send message button is not aligned with the other color gradients used in ui

**Comment by dhruv-4444** [comment]
i am done with the editing will give a pull request soon just testing the code there is no issues and bug anymore in my code

**Comment by rohitja26** [comment]
okk
