### ISSUE TITLE
Light/Dark Mode Consistency Across Pages

### ISSUE THREAD

**Issue by KhushiParekh** [Gyanthakur/Dev_Profiles#306]
## 📝 Description
There is an inconsistency in light/dark mode persistence across different pages. For example, if a user selects light mode on the landing page and navigates to the "Contact Us" page, the default dark mode is applied instead of maintaining the user's selection.

### 📷 Screenshot or Visual Reference (optional)
<img width="1431" alt="landing page" src="https://github.com/user-attachments/assets/62dc8ba1-5f5b-4635-82e5-6bdf617d708c">

<img width="1400" alt="contact us" src="https://github.com/user-attachments/assets/b5d1687c-b0d1-4b62-969a-774a9aa256b1">

## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Set the site to light mode on the landing page.
  2. Navigate to the "Contact Us" page.
  3.Observe that the dark mode is applied instead of the light mode.
- **Expected behavior:** Light mode should be maintained when navigating to other pages.
- **Actual behavior:**The default dark mode is applied after navigating.

## 💡 Enhancement / Feature Request (if applicable)
improve user experience by maintaining mode consistency across the entire website. This will create a cohesive and seamless experience for users who prefer a specific mode.

I would like to take on this task and fix the issue. Please assign it to me!

**Comment by Gyanthakur** [comment]
#311
