### ISSUE TITLE
Improve the UI of Contact Us Page 

### ISSUE THREAD

**Issue by KhushiParekh** [Gyanthakur/Dev_Profiles#307]
## 📝 Description
The current UI of the "Contact Us" page can be enhanced to provide a more polished and user-friendly experience. This includes improvements to the overall layout, styling, and responsiveness, as well as ensuring that the UI adapts well to both light and dark modes for better visual consistency.

## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Navigate to the "Contact Us" page in both light and dark modes.
  2. Observe the UI and its visual alignment with the rest of the site.

- **Expected behavior:**The "Contact Us" page should have a cohesive and visually appealing design, consistent with other pages in both light and dark modes.
- **Actual behavior:** The current UI lacks refinement and could benefit from improvements in design and mode compatibility.

## 💡 Enhancement / Feature Request (if applicable)
Enhance the overall UI of the "Contact Us" page, making it more user-friendly and visually consistent, especially in both dark and light modes. This will improve the page’s appearance and usability, contributing to a more cohesive user experience across the website.

I can work on this task. Please assign it to me!

**Comment by Gyanthakur** [comment]
@KhushiParekh what's your update

**Comment by Gyanthakur** [comment]
ok

**Comment by KhushiParekh** [comment]
this was the previous light mode:
<img width="1437" alt="Screenshot 2024-10-19 at 4 14 48 PM" src="https://github.com/user-attachments/assets/9d2caaa3-2872-4b80-865a-0d05f45e7264">

and this is the updated one:
<img width="1437" alt="Screenshot 2024-10-19 at 4 15 20 PM" src="https://github.com/user-attachments/assets/4911d660-22dd-4f82-91c5-157f7d462114">

 this is the dark mode of it:
<img width="1439" alt="Screenshot 2024-10-19 at 4 16 26 PM" src="https://github.com/user-attachments/assets/160a74c2-250d-405c-94f3-a3554ac04877">

The colours go with those of your theme
if looks good then let me know ill raise a pull request

**Comment by Gyanthakur** [comment]
@KhushiParekh raise pr.

**Comment by Gyanthakur** [comment]
#311
