### ISSUE TITLE
Project section make responsive one div for "URL, Project name, deploy link

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#317]
![Screenshot 2024-10-27 173743](https://github.com/user-attachments/assets/f1234e28-ebe0-44e6-8573-43a55863a8f3)

**Comment by Gyanthakur** [comment]
Who wants to work on it? Comment here

**Comment by Gyanthakur** [comment]
Who wants to work on it? Comment here

make changes for all components.

**Comment by khandelwal20sid** [comment]
@Gyanthakur  I'll work on it

**Comment by khandelwal20sid** [comment]
@Gyanthakur, PR created, pls check
