### ISSUE TITLE
Default Profile Image

### ISSUE THREAD

**Issue by ashish-bazad** [Gyanthakur/Dev_Profiles#33]
I want to add some more padding and create a default user profile image. @Gyanthakur Please assign this to me.
<img width="1680" alt="Screenshot 2023-10-15 at 9 37 52 PM" src="https://github.com/Gyanthakur/Dev_Profiles/assets/119102832/5e761a4d-c728-4dc6-a7cf-090a747b3ddc">

**Comment by ashish-bazad** [comment]
<img width="1680" alt="Screenshot 2023-10-15 at 9 40 44 PM" src="https://github.com/Gyanthakur/Dev_Profiles/assets/119102832/25e62f43-4de1-4dbe-8f17-7a74f036cdcd">
@Gyanthakur Please tell me why is this happening

**Comment by Gyanthakur** [comment]
done by @ashish-bazad
