### ISSUE TITLE
Add : Footer section on webpage

### ISSUE THREAD

**Issue by yube01** [Gyanthakur/Dev_Profiles#40]
Adding footer section on webpage which include copyright logo and it's details

**Comment by Gyanthakur** [comment]
> > Adding footer section on webpage which include copyright logo and it's details
> 
> @yube01 before adding read carefully how to contribute

**Comment by Gyanthakur** [comment]
> Adding footer section on webpage which include copyright logo and it's details

@yube01 go ahead
