### ISSUE TITLE
Redesign profile card , and assest optimizations for better loading

### ISSUE THREAD

**Issue by aditya4567uk** [Gyanthakur/Dev_Profiles#44]
hi

i can redesign the card to look even better.
![Capture](https://github.com/Gyanthakur/Dev_Profiles/assets/86232529/e482e077-b947-47bf-8d62-2872021a8d18)

can you pls assign me this task and this design is matching with the website even more :)

i can add assest optimizations for better loading

**Comment by Gyanthakur** [comment]
> hi
> 
> i can redesign the card to look even better. ![Capture](https://user-images.githubusercontent.com/86232529/275602097-e482e077-b947-47bf-8d62-2872021a8d18.JPG)
> 
> can you pls assign me this task and this design is matching with the website even more :)
> 
> i can add assest optimizations for better loading

after pushing the changes, create pr
