### ISSUE TITLE
chore: Refactor of index.html

### ISSUE THREAD

**Issue by bhishekprajapati** [Gyanthakur/Dev_Profiles#47]
Problem: index.html file is getting lengthier due to code duplication. As more dev profiles keeps on increasing the html file size will increase. Which can also affect the page load speed and maintainability of the project.

Solution: We can take a component based approach and abstract the component in vanilla js and separate the dev profile data. This will make the project more clean and a lot more maintainable with other benefits like reduced file sizes.

I'd like to work on this issue.

**Comment by Gyanthakur** [comment]
> Problem: index.html file is getting lengthier due to code duplication. As more dev profiles keeps on increasing the html file size will increase. Which can also affect the page load speed and maintainability of the project.
> 
> Solution: We can take a component based approach and abstract the component in vanilla js and separate the dev profile data. This will make the project more clean and a lot more maintainable with other benefits like reduced file sizes.
> 
> I'd like to work on this issue.

start your work
