### ISSUE TITLE
change  card designe 

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#54]
<img width="960" alt="image" src="https://github.com/Gyanthakur/Dev_Profiles/assets/98226958/7631da1b-4e5c-4a2a-89b3-f872404b07fb">

make changes according to dark as well as light mode

**Comment by OkenHaha** [comment]
Hello, I can work on this immediately, can you please assign this to me?

**Comment by ANIKETRAJ28** [comment]
i want to contribute to this project please assign me the project

**Comment by Gyanthakur** [comment]
> i want to contribute to this project please assign me the project

@ANIKETRAJ28 assigned to you
