### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by hanzalahwaheed** [Gyanthakur/Dev_Profiles#56]
Some Padding and Margins can be given to the Footer to improve the aesthetics of the website.
This is how it looks right now:
![image](https://github.com/Gyanthakur/Dev_Profiles/assets/101456741/7c558a2a-90e4-4798-b2d6-d0a46a6630ed)

**Comment by hanzalahwaheed** [comment]
Can I work on this under Hacktoberfest please?

**Comment by Gyanthakur** [comment]
> Can I work on this under Hacktoberfest please?

@hanzalahwaheed start your working

**Comment by ANIKETRAJ28** [comment]
can i contribute on this.

**Comment by hanzalahwaheed** [comment]
I have been assigned to this issue and I have already created a PR regarding it

**Comment by ANIKETRAJ28** [comment]
ok no problem
