### ISSUE TITLE
Add YOUR profile (Hacktober Fest)

### ISSUE THREAD

**Issue by abrehan2** [Gyanthakur/Dev_Profiles#6]
Hi,

I will add my details in the index.html file.

Best,
Rehan.

**Comment by abhi87374** [comment]
I will also add my details in the index.html file.
Regards ,
Abhikumar

**Comment by Shivam-Batham** [comment]
/ Assign me 
i also want to add my profile.

**Comment by Gyanthakur** [comment]
> [Oct 14, 2023](#event-10652718565)

add profile and create PR

**Comment by NickSahu** [comment]
Hello ,
I have added my profile and created pull request Kindly merge it .

**Comment by ShaikhMudassir7** [comment]
Assign me I want to create profile

**Comment by Gyanthakur** [comment]
> Hello , I have added my profile and created pull request Kindly merge it .

done

**Comment by Gyanthakur** [comment]
> Assign me I want to create profile

assign to you

**Comment by aditya4567uk** [comment]
I am also creating my profile in index .html

**Comment by hanzalahwaheed** [comment]
@Gyanthakur I would like to create my profile as well.

**Comment by vikas-parmar** [comment]
Hi,

I am going to add my details in the index.html file.

Best,
Vikas Parmar

**Comment by 1LAV1** [comment]
hi @Gyanthakur 
I am going to add my details in the index.html file.

**Comment by Gyanthakur** [comment]
> hi @Gyanthakur I have added my details in index.html file and generated a pull request please merge it .

done @1LAV1

**Comment by Gyanthakur** [comment]
> Hi,
> 
> I am going to add my details in the index.html file.
> 
> Best, Vikas Parmar

@vikas-parmar firstly follow the account and add your profie then create pull request

**Comment by Gyanthakur** [comment]
> firstly follow the account and add your profie then create pull request

firstly follow the account and add your profie then create pull request

**Comment by Shivam-Batham** [comment]
@Gyanthakur I made a PR please merge it.

**Comment by harrishDev** [comment]
@Gyanthakur assign me 
i will add my profile card and fix the footer design
