### ISSUE TITLE
fix the light mode

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#61]
![image](https://github.com/Gyanthakur/Dev_Profiles/assets/98226958/be61e9fb-6dd3-4b24-b0d0-956745042ae2)

## In light_mode invisible the text under the icon  fix it
![image](https://github.com/Gyanthakur/Dev_Profiles/assets/98226958/12a77051-d46a-411a-bbe7-52bbda13a8b2)

**Comment by Virtual4087** [comment]
i would like to work on this

**Comment by Raman01010010** [comment]
please assign , i want to work on it.

**Comment by Virtual4087** [comment]
Looks like i submitted a pr before being assigned but feel free to check it out.
