### ISSUE TITLE
Add social media  icon in footer section

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#62]

**Comment by the-shivam-gupta** [comment]
Could you please specify which links you'd like to include in the footer, and also provide the corresponding URLs for each of them?

**Comment by Gyanthakur** [comment]
> Could you please specify which links you'd like to include in the footer, and also provide the corresponding URLs for each of them?


LinkedIn, Twitter, Facebook, Instagram, YouTube

**Comment by the-shivam-gupta** [comment]
It won't include links that need to be redirected to your social account?

**Comment by Gyanthakur** [comment]
> It won't include links that need to be redirected to your social account?

Include official url not any user url

**Comment by the-shivam-gupta** [comment]
That's what i'm asking provide me the links for those sites

**Comment by Pritee-gupta-jpg** [comment]
Please assign this to me.

**Comment by harrishDev** [comment]
@Gyanthakur can you assign me and share the official url's of all socials

**Comment by Gyanthakur** [comment]
> That's what i'm asking provide me the links for those sites

LinkedIn: https://www.linkedin.com/in/gyan-pratap-singh-275785236/
Twitter: https://twitter.com/gps_96169
Facebook: https://m.facebook.com/profile.php?eav=AfaQiAnLMKoJt9fhAP0mpclv59dhzAMBnCy-rfJi2qawDv01IOkuI4RSxLQFG4508J0&paipv=0
Instagram: https://www.instagram.com/gp.singh.ro.ckstar4438/
YouTube: http://www.youtube.com/

**Comment by Gyanthakur** [comment]
one who creates it first will be accepted, Firstly follow the account, and then add the footer.

**Comment by harrishDev** [comment]
@Gyanthakur you haven't assigned me yet

**Comment by Gyanthakur** [comment]
> @Gyanthakur you haven't assigned me yet

follow the account before create Pull Request

**Comment by Gyanthakur** [comment]
> Please assign this to me.

start your work @Pritee-gupta-jpg
