### ISSUE TITLE
Same icon in dark as well as light mode and Font of the title is not appealing

### ISSUE THREAD

**Issue by inviBeast** [Gyanthakur/Dev_Profiles#67]
Sun icon should be present for light mode and the moon for dark mode.The font of the title needs to be replaced.

![hacktoberfest23](https://github.com/Gyanthakur/Dev_Profiles/assets/99094157/1fd83d11-6a39-46ab-b992-1fa402955716)

**Comment by inviBeast** [comment]
i want to work on this.

**Comment by Gyanthakur** [comment]
> i want to work on this.

start your work
