### ISSUE TITLE
change frontend designe

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#69]
#### change design by using linear gradient color

**Comment by AryanShriv** [comment]
I can do it.

Can you please brief me a bit, about what you want in the design and assign it to me?

Thank you.

**Comment by Gyanthakur** [comment]
> I can do it.
> 
> Can you please brief me a bit, about what you want in the design and assign it to me?
> 
> Thank you.

change according to your choice
