### ISSUE TITLE
We can add animations to the cards 

### ISSUE THREAD

**Issue by Divyanshi014** [Gyanthakur/Dev_Profiles#80]
We can add animations or other styling to make it even more attractive

**Comment by Gyanthakur** [comment]
> We can add animations or other styling to make it even more attractive

start your work @Divyanshi014

**Comment by Divyanshi014** [comment]
@Gyanthakur I was working on it.

**Comment by Gyanthakur** [comment]
> @Gyanthakur I was working on it. Can you please open it I'll do a PR today itself

okey, if your card animation is more attractive then I'll merged

**Comment by Gyanthakur** [comment]
@Divyanshi014 this animation add project card also
