### ISSUE TITLE
Change footer design

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#90]

**Comment by saakshi002** [comment]
Hi can you assign me this task? @Gyanthakur

**Comment by Gyanthakur** [comment]
> Hi can you assign me this task? @Gyanthakur

start your work @saakshi002

**Comment by harrishDev** [comment]
assign me with this issue @Gyanthakur 
i'll fix it

**Comment by Gyanthakur** [comment]
> ![Screenshot (183)](https://user-images.githubusercontent.com/78097586/278880845-4b9990cf-051b-4582-89e9-afa000157add.png) assign me with this issue @Gyanthakur i fixed it

create your pr

**Comment by Gyanthakur** [comment]
> ![Screenshot (183)](https://user-images.githubusercontent.com/78097586/278880845-4b9990cf-051b-4582-89e9-afa000157add.png) assign me with this issue @Gyanthakur i fixed it

assigned already @saakshi002 

so wait

**Comment by harrishDev** [comment]
but i have already fixed the issue @Gyanthakur 
allow multiple submissions for this issue
