### ISSUE TITLE
Add footer in project section

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/Dev_Profiles#95]

**Comment by harshvyas-22** [comment]
i would love to contribute please assign to me

**Comment by SeaBebop** [comment]
Attempted addition at pr https://github.com/Gyanthakur/Dev_Profiles/pull/96
![footer](https://github.com/Gyanthakur/Dev_Profiles/assets/54507045/8f4c4870-236f-4e97-990e-4f15c73e64d0)
