### ISSUE TITLE
Bug: Dark and light theme toggle.

### ISSUE THREAD

**Issue by the-shivam-gupta** [Gyanthakur/Dev_Profiles#99]
When we toggle to the light theme the text for the smaller screen gets overlaps to it.
Image 1:
![image](https://github.com/Gyanthakur/Dev_Profiles/assets/109647722/ac526d1b-fbee-4bba-82df-6772138c5087)

Image2:
![image](https://github.com/Gyanthakur/Dev_Profiles/assets/109647722/52966be1-89f7-405b-9cfd-41d9c1e91866)

Also, in the dark theme, the name of the profile holder is not visible:

![image](https://github.com/Gyanthakur/Dev_Profiles/assets/109647722/8868c992-80c2-4923-8d7a-9b7daefa0e7a)

**Comment by Gyanthakur** [comment]
#100

**Comment by Gyanthakur** [comment]
#100
